update workflows

diff --git a/.github/workflows/release_pr_build.yml b/.github/workflows/release_pr_build.yml
--- a/.github/workflows/release_pr_build.yml
+++ b/.github/workflows/release_pr_build.yml
@@ -13,7 +13,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  build:
+  release-pr-build:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout GCM
@@ -25,6 +25,16 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
     
+    - name: Get Version
+      run: |
+        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml)" >> "$GITHUB_ENV"
+
+    - name: Version Is Snapshot
+      if: ${{ endsWith(env.version, 'SNAPSHOT') }}
+      run: |
+        echo "::error Version is a SNAPSHOT. Update version to proper version."
+        exit 1
+
     - name: Build GCM
       run: mvn clean install -Prelease --file pom.xml
 
